//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace controller
{
	using model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CartsController
	{
		public virtual IEnumerable<Cart> carts
		{
			get;
			set;
		}

		public virtual MainController mainController
		{
			get;
			set;
		}

		public CartsController(MainController mainController)
		{
		}

	}
}

