//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputController
	{
		public MainController mainController
		{
			get;
			set;
		}

		public InputController(MainController mainController)
		{
            this.mainController = mainController;
		}


        public void enterInputLoop()
        {
            while (true) // Loop indefinitely
            {
                ConsoleKeyInfo key = Console.ReadKey(); // Get string from user
                switch (key.KeyChar)
                {
                    case 'q':
                        return;
                }
            }
        }
    }
}

