//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace controller
{
	using model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MapController
	{
        public virtual Dictionary<int, Dictionary<int, Field>> fields
		{
			get;
			set;
		}

		public virtual MainController mainController
		{
			get;
			set;
		}

		public MapController(MainController mainController)
		{
            this.mainController = mainController;
		}

        public void GenerateMap()
        {
            fields = new Dictionary<int, Dictionary<int, Field>>();
            
            // First row only water.
            Dictionary<int, Field> row = new Dictionary<int, Field>();
            for (int i = 0; i < 13; i++)
            {
                row[i] = new Water();
            }
            fields[0] = row; 
        }
    }
}

