//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public virtual MainController mainController
	{
		get;
		set;
	}

	public virtual void Initialize()
	{
        mainController = new MainController();
        mainController.Initialize();
	}

	public virtual void Terminate()
	{
        mainController = null;
	}

}

