//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using view;

public class Game
{
	public virtual View view
	{
		get;
		set;
	}

	public virtual MapController mapController
	{
		get;
		set;
	}

	public virtual InputController inputController
	{
		get;
		set;
	}

	public virtual CartsController cartsController
	{
		get;
		set;
	}

	public virtual ShipsController shipsController
	{
		get;
		set;
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

}

