//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ship : WaterVisitor
{
	private int cargo
	{
		get;
		set;
	}

	public static int MAX_CARGO
	{
		get;
		private set;
	}

	public virtual bool IsDocked()
	{
		throw new System.NotImplementedException();
	}

}

