//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Warehouse : LandField
{
	public virtual string name
	{
		get;
		set;
	}

	public virtual TrainRails GetTrainRails()
	{
		throw new System.NotImplementedException();
	}

	public virtual char ToChar()
	{
		throw new System.NotImplementedException();
	}

}

