//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace view
{
	using controller;
    using model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class View
	{
        public enum Screen
        {
            START,
            GAME,
            END
        }

        public Screen currentScreen
        {
            get;
            set;
        }

		public MainController mainController
		{
			get;
			set;
		}

		public View(MainController mainController)
		{
            this.mainController = mainController;
		}

        private void Clear()
        {
            Console.Clear();
            Console.WriteLine("!!!!!GoudKoorts!!!!!");
            Console.WriteLine();
        }

        public void RenderStartScreen()
        {
            // Clear the console.
            Clear();

            // Write the start lines.
            Console.WriteLine("Welcome to GoudKoorts!");
            Console.WriteLine();
            Console.WriteLine("Press 's' to start.");
            Console.WriteLine("Press 'q' to quit.");

            currentScreen = Screen.START;
        }

        public void RenderGameScreen(Map map)
        {
            // Clear the console.
            Clear();

            // Render the map.
            foreach (KeyValuePair<int, Dictionary<int, Field>> row in map.fields)
            {
                int previousIndex = -1;
                foreach (KeyValuePair<int, Field> field in row.Value)
                {
                    // Fill empty squares.
                    for (int i = previousIndex + 1; i < field.Key; i++)
                        Console.Write(' ');

                    previousIndex = field.Key;

                    Console.Write(field.Value.ToChar());
                }
                Console.WriteLine();
            }

            Console.WriteLine();
            Console.WriteLine("Press keys 1 through 5 to control the train track switches.");
            Console.WriteLine("Press 'q' to quit.");

            currentScreen = Screen.GAME;
        }

        public void RenderEndScreen()
        {
            // Clear the console.
            Clear();

            // Write the score.
            Console.WriteLine("The End!");

            Console.WriteLine();
            Console.WriteLine("Press 's' to start again.");
            Console.WriteLine("Press 'q' to quit.");

            currentScreen = Screen.END;
        }

        public void RenderInvalidInputWarning(char key)
        {
            Console.Write("\rInvalid key: {0}.", key);
        }
	}
}

