//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace view
{
	using controller;
    using model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class View
	{
		public MainController mainController
		{
			get;
			set;
		}

		public View(MainController mainController)
		{
            this.mainController = mainController;
		}

        public void Clear()
        {
            Console.Clear();
            Console.WriteLine("!!!!!GoudKoorts!!!!!");
            Console.WriteLine();
        }

        public void RenderStartScreen()
        {
            // Clear the console.
            Clear();

            // Write the start lines.
            Console.WriteLine("Welcome to GoudKoorts!");
            Console.WriteLine();
            Console.WriteLine("Press 's' to start.");
            Console.WriteLine("Press 'q' to quit.");
        }

        public void RenderGameScreen()
        {
            // Clear the console.
            Clear();

            // Render the map.
            foreach (KeyValuePair<int, Dictionary<int, Field>> row in mainController.mapController.fields)
            {
                foreach (KeyValuePair<int, Field> field in row.Value)
                {
                    Console.Write(field.Value.ToChar());
                }
                Console.WriteLine();
            }

            Console.WriteLine();
            Console.WriteLine("Press keys 1 through 5 to control the train track switches.");
            Console.WriteLine("Press 'q' to quit.");
        }

        public void RenderEndScreen()
        {
            // Clear the console.
            Clear();

            // Write the score.
            Console.WriteLine("The End!");

            Console.WriteLine();
            Console.WriteLine("Press 's' to start again.");
            Console.WriteLine("Press 'q' to quit.");
        }
	}
}

