//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace view
{
	using controller;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class View
	{
		public virtual MainController mainController
		{
			get;
			set;
		}

		public View(MainController mainController)
		{
            this.mainController = new MainController();
		}

        public void RenderStartScreen()
        {
            // Clear the console.
            Console.Clear();

            // Write the start lines.
            Console.WriteLine("Welcome to GoudKoorts! Press any key to start.");
        }
	}
}

