//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Fairway : WaterTrack
	{
        public Fairway(int x, int y, WaterTrack nextTrack) : base(x, y, nextTrack) { }

        public override char ToChar()
        {
            return '~';
        }
	}
}

