//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Field
	{
        public int x { get; set; }

        public int y { get; set; }

        public Field(int x, int y)
        {
            this.x = x;
            this.y = y;
        }

        public abstract char ToChar();
	}
}

