//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Map
	{
        public SortedDictionary<int, SortedDictionary<int, Field>> fields { get; set; }

        public int mapSizeX { get; set; }

        public int mapSizeY { get; set; }
	}
}

