//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Parking : TrainRails
	{
        public Parking(int x, int y, TrainRails nextTrack, Axis axis) : base(x, y, nextTrack, axis) { }

        public override char ToChar()
        {
            return '=';
        }
	}
}

