//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Switch : TrainRails
	{
        public enum Direction
        {
            LEFT,
            RIGHT
        }

        public enum ActiveTrack
        {
            UP,
            DOWN
        }

        public TrainRails trackUp { get; set; }

        public TrainRails trackDown { get; set; }

        public Direction direction { get; set; }

        public ActiveTrack activeTrack { get; set; }

        public Switch(int x, int y, TrainRails nextTrack, Direction direction, TrainRails trackUp, TrainRails trackDown) : base(x, y, nextTrack, Axis.HORIZONTAL)
        {
            this.direction = direction;
            this.trackUp = trackUp;
            this.trackDown = trackDown;
        }

		public override char ToChar()
		{
            if (direction == Direction.LEFT)
                if (activeTrack == ActiveTrack.UP)
                    return '\\';
                else
                    return '/';
            else
                if (activeTrack == ActiveTrack.UP)
                    return '/';
                else
                    return '\\';
		}

        public override Track nextTrack
        {
            get
            {
                if (nextTrack != null)
                    return nextTrack;
                if (activeTrack == ActiveTrack.UP)
                    return trackUp;
                else
                    return trackDown;
            }
            set { }
        }

        public void Shift()
        {
            if (activeTrack == ActiveTrack.UP)
                activeTrack = ActiveTrack.DOWN;
            else
                activeTrack = ActiveTrack.UP;
        }
	}
}

