//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Track : Field
	{
        public enum VisitAllowed
        {
            ALLOWED,
            ALREADY_HAVE_VISITOR,
        }

        public virtual Track nextTrack { get; set; }

        public Visitor visitor { get; set; }

        public Track(int x, int y, Track nextTrack) : base(x, y)
        {
            this.nextTrack = nextTrack;
        }

        public virtual VisitAllowed AllowVisit()
        {
            if (visitor != null)
                return VisitAllowed.ALLOWED;
            else
                return VisitAllowed.ALREADY_HAVE_VISITOR;
        }
	}
}

