//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TrainRails : LandTrack
	{
        public enum Axis
        {
            HORIZONTAL,
            VERTICAL
        }

        public Axis axis { get; set; }

        public TrainRails(int x, int y, TrainRails nextTrack, Axis axis)
            : base(x, y, nextTrack)
        {
            this.axis = axis;
        }

        public override char ToChar()
        {
            if (axis == Axis.HORIZONTAL)
                return '-';
            else
                return '|';
        }
	}
}

