//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Warehouse : Field
	{
		public char name { get; set; }

        public Warehouse(int x, int y, char name) : base(x, y)
        {
            this.name = name;
        }

		public override char ToChar()
		{
            return name;
		}
	}
}

