//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Water : Field
	{
        public Water(int x, int y) : base(x, y) { }

		public override char ToChar()
		{
            return '~';
		}
	}
}

